export const GET_ACTIONS = 'GET_ACTIONS';
export const GET_ACTIONS_SUCCESS = 'GET_ACTIONS_SUCCESS';
export const GET_ACTIONS_FAIL = 'GET_ACTIONS_FAIL';
export const GET_ACTIONS_HIS = 'GET_ACTIONS_HIS';
export const GET_ACTIONS_HIS_SUCCESS = 'GET_ACTIONS_HIS_SUCCESS';
export const GET_ACTIONS_HIS_FAIL = 'GET_ACTIONS_HIS_FAIL';