export const GET_FAQS = 'GET_FAQS';
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS';
export const GET_FAQS_FAIL = 'GET_FAQS_FAIL';
export const DELETE_FAQS = 'DELETE_FAQS';
export const DELETE_FAQS_SUCCESS = 'DELETE_FAQS_SUCCESS';
export const DELETE_FAQS_FAIL = 'DELETE_FAQS_FAIL';